version: "3.9"

services:
  api:
    build: ./services/api
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres # pragma: allowlist secret

      S3_ENDPOINT: http://localstack:4566
      S3_BUCKET: portals-dev
      S3_ACCESS_KEY_ID: test
      S3_SECRET_ACCESS_KEY: test # pragma: allowlist secret

      GITHUB_APP_ID: ${GITHUB_APP_ID}
      GITHUB_APP_PRIVATE_KEY: ${GITHUB_APP_PRIVATE_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - db
      - localstack

  db:
    image: supabase/postgres:15.8.1.049
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres # pragma: allowlist secret
    ports:
      - "5432:5432"
    volumes:
      - supabase_db_data:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack
    restart: unless-stopped
    environment:
      SERVICES: s3
      DEFAULT_REGION: us-east-1
    ports:
      - "4566:4566"
    volumes:
      - localstack_data:/var/lib/localstack

volumes:
  supabase_db_data:
  localstack_data:
