import { generateAttributes } from "#shared/lm/tools/generate-entity-attributes.js";
import { ToolContext } from "#shared/lm/tools/tools.utils.js";
import { TextModelController } from "../text-model-controller.js";
import {
    CharacterAttributes,
} from "../../types/index.js";

/**
     * Produces a complete CharacterAttributes object from a partial.
     * Fields already set by the caller are preserved exactly — only missing
     * or empty fields are generated by the LLM.
     */
export async function generateCharacterAttributes({
    partial,
    imageGcsUri,
    mimeType
}: {
    partial: Partial<CharacterAttributes>,
    imageGcsUri?: string,
    mimeType?: string
},
    context: ToolContext<TextModelController>
): Promise<CharacterAttributes> {

    return generateAttributes({
        schema: CharacterAttributes,
        partial,
        entityDescription: "character profile",
        imageGcsUri,
        mimeType
    },
        context);
}