import { generateAttributes } from "#shared/lm/tools/generate-entity-attributes.js";
import { ToolContext } from "#shared/lm/tools/tools.utils.js";
import { TextModelController } from "../text-model-controller.js";
import {
    LocationAttributes,
} from "../../types/index.js";

/**
 * Produces a complete LocationAttributes object from a partial.
 * Fields already set by the caller are preserved exactly — only missing
 * or empty fields are generated by the LLM.
 */
export async function generateLocationAttributes({
    partial,
    images,
}: {
    partial: Partial<LocationAttributes>,
    images?: { gcsUri: string, mimeType: string }[],
},
    context: ToolContext<TextModelController>
): Promise<LocationAttributes> {

    return generateAttributes({
        schema: LocationAttributes,
        partial,
        entityDescription: "location profile",
        images
    },
        context);
}