import { generateEntityAttributes } from "#shared/lm/tools/generate-entity-attributes.js";
import { ToolContext } from "#shared/lm/tools/tools.utils.js";
import { TextModelController } from "../../text-model-controller.js";
import {
    CharacterAttributes,
    LocationAttributes,
    SceneAttributes,
    UploadResult,
} from "../../../types/index.js";
import { ProjectRepository } from "#shared/services/project-repository.js";

/**
 * Produces a complete SceneAttributes object from a partial.
 * Fields already set by the caller are preserved exactly — only missing
 * or empty fields are generated by the LLM.
 * Supply context (character names, location name) so the LLM can ground
 * cinematic details in the actual cast and setting.
 * Entity-relationship fields (characterReferenceIds, locationReferenceId,
 * characterIds, locationId) are NOT generated — they must be set by the caller.
 */
export async function generateSceneAttributes(
    inputs: {
        partial: Partial<SceneAttributes> & { id: string };
        characters?: (Partial<CharacterAttributes> & { referenceId: string })[];
        location?: (Partial<LocationAttributes> & { referenceId: string });
        images?: UploadResult[];
    }[],
    context: ToolContext<TextModelController> & { projectRepository: ProjectRepository }
): Promise<SceneAttributes[]> {

    const entityType = "scene";
    const results = await generateEntityAttributes({
        schema: SceneAttributes,
        entities: inputs.map(input => ({
            data: input.partial,
            entityType,
            images: input.images
        })),
        entityDescription: "scene specification",
    },
        context
    );

    return results.map((result) => {
        if (!result.success) {
            throw new Error(`[Trace: ${context.traceId}] Failed to generate scene attributes for ID ${result.id}: ${result.error?.message}`);
        }
        return result.data;
    });
}