"""initial

Phase: EXPAND

Revision ID: 0dda306ba14b
Revises:
Create Date: 2026-06-25 00:37:49.735369

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0dda306ba14b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "credit_transaction",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("balance_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reference_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("reference_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("credit_transaction", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_credit_transaction_user_id"), ["user_id"], unique=False)

    op.create_table(
        "feature_gate",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("feature", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tier", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("feature", "tier", name="uq_feature_gate_feature_tier"),
    )
    with op.batch_alter_table("feature_gate", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_feature_gate_feature"), ["feature"], unique=False)
        batch_op.create_index(batch_op.f("ix_feature_gate_tier"), ["tier"], unique=False)

    op.create_table(
        "job",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("flow_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("queued", "in_progress", "completed", "failed", "cancelled", "timed_out", name="job_status_enum"),
            nullable=False,
        ),
        sa.Column("created_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("type", sa.Enum("workflow", "ingestion", "evaluation", name="job_type_enum"), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("asset_id", sa.Uuid(), nullable=True),
        sa.Column("asset_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("job_id"),
    )
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_job_asset_id"), ["asset_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_job_flow_id"), ["flow_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_job_job_id"), ["job_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_job_type"), ["type"], unique=False)
        batch_op.create_index(batch_op.f("ix_job_user_id"), ["user_id"], unique=False)

    op.create_table(
        "media_objects",
        sa.Column("data", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ref_count", sa.Integer(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_referenced_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("data"),
    )
    op.create_table(
        "message",
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("sender", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sender_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("context_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("error", sa.Boolean(), nullable=False),
        sa.Column("edit", sa.Boolean(), nullable=False),
        sa.Column("files", sa.JSON(), nullable=True),
        sa.Column("properties", sa.JSON(), nullable=True),
        sa.Column("category", sa.Text(), nullable=True),
        sa.Column("content_blocks", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("flow_id", sa.Uuid(), nullable=True),
        sa.Column("session_metadata", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notification",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("message", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("reference_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("reference_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_notification_user_id"), ["user_id"], unique=False)

    op.create_table(
        "stripeproduct",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("stripe_product_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("stripe_price_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tier", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("product_credits", sa.Integer(), nullable=True),
        sa.Column("unit_amount", sa.Integer(), nullable=True),
        sa.Column("currency", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("product_metadata", sa.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("stripeproduct", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_stripeproduct_stripe_price_id"), ["stripe_price_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_stripeproduct_stripe_product_id"), ["stripe_product_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_stripeproduct_tier"), ["tier"], unique=False)

    op.create_table(
        "teams",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_teams_name"), ["name"], unique=False)

    op.create_table(
        "transaction",
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("vertex_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("target_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("inputs", sa.JSON(), nullable=True),
        sa.Column("outputs", sa.JSON(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("flow_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("profile_image", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("create_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.Column("store_api_key", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("optins", sa.JSON(), nullable=True),
        sa.Column("stripe_customer_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("stripe_subscription_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("subscription_tier", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("subscription_status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("current_period_end", sa.DateTime(), nullable=True),
        sa.Column("cancel_at_period_end", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_username"), ["username"], unique=True)

    op.create_table(
        "user_credit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("allowance_balance", sa.Integer(), nullable=False),
        sa.Column("purchased_balance", sa.Integer(), nullable=False),
        sa.Column("total_earned", sa.Integer(), nullable=False),
        sa.Column("total_spent", sa.Integer(), nullable=False),
        sa.Column("trial_credits_used", sa.Boolean(), nullable=False),
        sa.Column("last_allowance_date", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_credit", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_credit_user_id"), ["user_id"], unique=True)

    op.create_table(
        "apikey",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("total_uses", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("api_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("api_key_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    with op.batch_alter_table("apikey", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_apikey_api_key"), ["api_key"], unique=True)
        batch_op.create_index(batch_op.f("ix_apikey_api_key_hash"), ["api_key_hash"], unique=False)
        batch_op.create_index(batch_op.f("ix_apikey_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_apikey_user_id"), ["user_id"], unique=False)

    op.create_table(
        "deployment_provider_account",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("provider_tenant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("provider_key", sa.Enum("watsonx-orchestrate", name="deployment_provider_key_enum"), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("api_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "provider_key", "name", name="uq_deployment_provider_account_provider_name"),
        sa.UniqueConstraint(
            "user_id", "provider_url", "provider_tenant_id", name="uq_deployment_provider_account_user_url_tenant"
        ),
    )
    with op.batch_alter_table("deployment_provider_account", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_deployment_provider_account_provider_key"), ["provider_key"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_deployment_provider_account_provider_tenant_id"), ["provider_tenant_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_deployment_provider_account_user_id"), ["user_id"], unique=False)

    op.create_table(
        "folder",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("auth_settings", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("generation_rules", sa.JSON(), nullable=False),
        sa.Column("style_references", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["parent_id"], ["folder.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="unique_folder_name"),
    )
    with op.batch_alter_table("folder", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_folder_name"), ["name"], unique=False)

    op.create_table(
        "sso_config",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("enforce_sso", sa.Boolean(), nullable=False),
        sa.Column("client_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("client_secret_encrypted", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("discovery_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("redirect_uri", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("scopes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("email_claim", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("username_claim", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id_claim", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("token_endpoint", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("authorization_endpoint", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("jwks_uri", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("issuer", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sso_user_profile",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("sso_provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sso_user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sso_last_login_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sso_user_profile", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sso_user_profile_email"), ["email"], unique=False)
        batch_op.create_index(batch_op.f("ix_sso_user_profile_user_id"), ["user_id"], unique=True)
        batch_op.create_index("uq_sso_user_profile_provider_user", ["sso_provider", "sso_user_id"], unique=True)

    op.create_table(
        "users_to_teams",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "team_id", name="uq_user_team"),
    )
    with op.batch_alter_table("users_to_teams", schema=None) as batch_op:
        batch_op.create_index("ix_users_to_teams_team_id", ["team_id"], unique=False)
        batch_op.create_index("ix_users_to_teams_user_id", ["user_id"], unique=False)

    op.create_table(
        "variable",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("default_fields", sa.JSON(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "blocks",
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("dialogue", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("happened_at", sa.DateTime(), nullable=True),
        sa.Column("is_notable", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("image_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("search_vector", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["folder.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    with op.batch_alter_table("blocks", schema=None) as batch_op:
        batch_op.create_index("idx_blocks_project_id", ["project_id"], unique=False)
        batch_op.create_index("idx_blocks_search", ["search_vector"], unique=False, postgresql_using="gin")

    op.create_table(
        "characters",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("reference_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("aliases", sa.JSON(), nullable=False),
        sa.Column("physical_traits", sa.JSON(), nullable=False),
        sa.Column("state", sa.JSON(), nullable=False),
        sa.Column("guidance_level", sa.Integer(), nullable=True),
        sa.Column("nap_uri", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("nap_commit_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["folder.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    with op.batch_alter_table("characters", schema=None) as batch_op:
        batch_op.create_index("characters_guidance_idx", ["guidance_level"], unique=False)
        batch_op.create_index(batch_op.f("ix_characters_name"), ["name"], unique=False)

    op.create_table(
        "deployment",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("resource_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("deployment_provider_account_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("deployment_type", sa.Enum("agent", name="deployment_type_enum"), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["deployment_provider_account_id"], ["deployment_provider_account.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["folder.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("deployment_provider_account_id", "name", name="uq_deployment_name_in_provider"),
        sa.UniqueConstraint(
            "deployment_provider_account_id", "resource_key", name="uq_deployment_resource_key_in_provider"
        ),
    )
    with op.batch_alter_table("deployment", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_deployment_deployment_provider_account_id"), ["deployment_provider_account_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_deployment_deployment_type"), ["deployment_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_deployment_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_deployment_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_deployment_resource_key"), ["resource_key"], unique=False)
        batch_op.create_index(batch_op.f("ix_deployment_user_id"), ["user_id"], unique=False)

    op.create_table(
        "file",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("folder_id", sa.Uuid(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["folder_id"], ["folder.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "user_id", "folder_id"),
    )
    with op.batch_alter_table("file", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_file_folder_id"), ["folder_id"], unique=False)

    op.create_table(
        "flow",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon_bg_color", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("gradient", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_component", sa.Boolean(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("webhook", sa.Boolean(), nullable=True),
        sa.Column("endpoint_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("mcp_enabled", sa.Boolean(), nullable=True),
        sa.Column("action_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("action_description", sa.Text(), nullable=True),
        sa.Column(
            "access_type",
            sa.Enum("PRIVATE", "PUBLIC", name="access_type_enum"),
            server_default=sa.text("'PRIVATE'"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("icon", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("locked", sa.Boolean(), nullable=True),
        sa.Column("folder_id", sa.Uuid(), nullable=True),
        sa.Column("fs_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(["folder_id"], ["folder.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("user_id", "endpoint_name", name="unique_flow_endpoint_name"),
        sa.UniqueConstraint("user_id", "name", name="unique_flow_name"),
    )
    with op.batch_alter_table("flow", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_flow_description"), ["description"], unique=False)
        batch_op.create_index(batch_op.f("ix_flow_endpoint_name"), ["endpoint_name"], unique=False)
        batch_op.create_index(batch_op.f("ix_flow_folder_id"), ["folder_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_flow_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_flow_user_id"), ["user_id"], unique=False)

    op.create_table(
        "locations",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("reference_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("mood", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("lighting_conditions", sa.JSON(), nullable=False),
        sa.Column("time_of_day", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("weather", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("color_palette", sa.JSON(), nullable=False),
        sa.Column("architecture", sa.JSON(), nullable=False),
        sa.Column("natural_elements", sa.JSON(), nullable=False),
        sa.Column("man_made_objects", sa.JSON(), nullable=False),
        sa.Column("ground_surface", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sky_or_ceiling", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("state", sa.JSON(), nullable=False),
        sa.Column("guidance_level", sa.Integer(), nullable=True),
        sa.Column("nap_uri", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("nap_commit_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["folder.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    with op.batch_alter_table("locations", schema=None) as batch_op:
        batch_op.create_index("locations_guidance_idx", ["guidance_level"], unique=False)

    op.create_table(
        "lore",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("happened_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["folder.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "props",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("reference_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("guidance_level", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("nap_uri", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("nap_commit_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["folder.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "flow_version",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("flow_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.CheckConstraint("version_number >= 1", name="check_version_number_positive"),
        sa.ForeignKeyConstraint(["flow_id"], ["flow.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("flow_id", "version_number", name="unique_flow_version_number"),
    )
    with op.batch_alter_table("flow_version", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_flow_version_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_flow_version_flow_id"), ["flow_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_flow_version_user_id"), ["user_id"], unique=False)

    op.create_table(
        "scenes",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("scene_index", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("start_time", sa.Float(), nullable=False),
        sa.Column("end_time", sa.Float(), nullable=False),
        sa.Column("duration", sa.Float(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("lyrics", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("musical_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("music_change", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("intensity", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("mood", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tempo", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("audio_evidence", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("transient_impact", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("audio_sync", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("transition_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("shot_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("camera_angle", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("camera_movement", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("composition", sa.JSON(), nullable=False),
        sa.Column("lighting", sa.JSON(), nullable=False),
        sa.Column("continuity_notes", sa.JSON(), nullable=False),
        sa.Column("character_reference_ids", sa.JSON(), nullable=False),
        sa.Column("location_reference_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("progress_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("guidance_level", sa.Integer(), nullable=True),
        sa.Column("nap_uri", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("nap_commit_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"]),
        sa.ForeignKeyConstraint(["project_id"], ["folder.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    with op.batch_alter_table("scenes", schema=None) as batch_op:
        batch_op.create_index("scenes_guidance_idx", ["guidance_level"], unique=False)

    op.create_table(
        "tag_registry",
        sa.Column("handle", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("entity_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("character_id", sa.Uuid(), nullable=True),
        sa.Column("location_id", sa.Uuid(), nullable=True),
        sa.Column("prop_id", sa.Uuid(), nullable=True),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"]),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"]),
        sa.ForeignKeyConstraint(["project_id"], ["folder.id"]),
        sa.ForeignKeyConstraint(["prop_id"], ["props.id"]),
        sa.PrimaryKeyConstraint("handle"),
    )
    with op.batch_alter_table("tag_registry", schema=None) as batch_op:
        batch_op.create_index(
            "idx_tag_handle_fuzzy",
            ["handle"],
            unique=False,
            postgresql_using="gin",
            postgresql_ops={"handle": "gin_trgm_ops"},
        )
        batch_op.create_index("idx_tag_scope", ["project_id"], unique=False)

    op.create_table(
        "trace",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sa.Enum("unset", "ok", "error", name="spanstatus"), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("total_latency_ms", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("flow_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["flow_id"], ["flow.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("trace", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_trace_flow_id"), ["flow_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_trace_session_id"), ["session_id"], unique=False)

    op.create_table(
        "asset_entries",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("scene_id", sa.Uuid(), nullable=True),
        sa.Column("character_id", sa.Uuid(), nullable=True),
        sa.Column("location_id", sa.Uuid(), nullable=True),
        sa.Column("prop_id", sa.Uuid(), nullable=True),
        sa.Column("file_id", sa.Uuid(), nullable=True),
        sa.Column("asset_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("head", sa.Integer(), nullable=False),
        sa.Column("best", sa.Integer(), nullable=False),
        sa.Column("best_locked_by_feedback", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"]),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"]),
        sa.ForeignKeyConstraint(["project_id"], ["folder.id"]),
        sa.ForeignKeyConstraint(["prop_id"], ["props.id"]),
        sa.ForeignKeyConstraint(["scene_id"], ["scenes.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    with op.batch_alter_table("asset_entries", schema=None) as batch_op:
        batch_op.create_index("idx_asset_entries_character", ["character_id"], unique=False)
        batch_op.create_index("idx_asset_entries_file", ["file_id"], unique=False)
        batch_op.create_index("idx_asset_entries_location", ["location_id"], unique=False)
        batch_op.create_index("idx_asset_entries_project", ["project_id"], unique=False)
        batch_op.create_index("idx_asset_entries_scene", ["scene_id"], unique=False)
        batch_op.create_index("idx_unq_char_asset", ["character_id", "asset_key"], unique=True)
        batch_op.create_index("idx_unq_file_asset", ["file_id", "asset_key"], unique=True)
        batch_op.create_index("idx_unq_loc_asset", ["location_id", "asset_key"], unique=True)
        batch_op.create_index(
            "idx_unq_project_asset",
            ["project_id", "asset_key"],
            unique=True,
            postgresql_where=sa.text(
                "scene_id IS NULL AND character_id IS NULL AND location_id IS NULL AND file_id IS NULL"
            ),
        )
        batch_op.create_index("idx_unq_scene_asset", ["scene_id", "asset_key"], unique=True)

    op.create_table(
        "flow_version_deployment_attachment",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("flow_version_id", sa.Uuid(), nullable=False),
        sa.Column("deployment_id", sa.Uuid(), nullable=False),
        sa.Column("provider_snapshot_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["deployment_id"], ["deployment.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["flow_version_id"], ["flow_version.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("flow_version_id", "deployment_id", name="uq_flow_version_deployment"),
    )
    with op.batch_alter_table("flow_version_deployment_attachment", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_flow_version_deployment_attachment_deployment_id"), ["deployment_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_flow_version_deployment_attachment_flow_version_id"), ["flow_version_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_flow_version_deployment_attachment_provider_snapshot_id"),
            ["provider_snapshot_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_flow_version_deployment_attachment_user_id"), ["user_id"], unique=False)

    op.create_table(
        "scenes_to_characters",
        sa.Column("scene_id", sa.Uuid(), nullable=True),
        sa.Column("character_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"]),
        sa.ForeignKeyConstraint(["scene_id"], ["scenes.id"]),
        sa.PrimaryKeyConstraint("scene_id", "character_id"),
    )
    op.create_table(
        "span",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "span_type",
            sa.Enum("chain", "llm", "tool", "retriever", "embedding", "parser", "agent", name="spantype"),
            nullable=False,
        ),
        sa.Column("status", sa.Enum("unset", "ok", "error", name="spanstatus"), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("inputs", sa.JSON(), nullable=True),
        sa.Column("outputs", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "span_kind",
            sa.Enum("INTERNAL", "CLIENT", "SERVER", "PRODUCER", "CONSUMER", name="spankind"),
            nullable=False,
        ),
        sa.Column("attributes", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("trace_id", sa.Uuid(), nullable=False),
        sa.Column("parent_span_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["parent_span_id"], ["span.id"]),
        sa.ForeignKeyConstraint(["trace_id"], ["trace.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("span", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_span_parent_span_id"), ["parent_span_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_span_trace_id"), ["trace_id"], unique=False)

    op.create_table(
        "asset_versions",
        sa.Column("asset_entry_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("data", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("media_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("user_feedback", sa.JSON(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["asset_entry_id"], ["asset_entries.id"]),
        sa.ForeignKeyConstraint(["media_id"], ["media_objects.data"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    with op.batch_alter_table("asset_versions", schema=None) as batch_op:
        batch_op.create_index("idx_asset_history_lookup", ["asset_entry_id", "version"], unique=False)
        batch_op.create_index("idx_entry_version", ["asset_entry_id", "version"], unique=False)
        batch_op.create_index("idx_unq_asset_version_seq", ["asset_entry_id", "version"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("asset_versions", schema=None) as batch_op:
        batch_op.drop_index("idx_unq_asset_version_seq")
        batch_op.drop_index("idx_entry_version")
        batch_op.drop_index("idx_asset_history_lookup")

    op.drop_table("asset_versions")
    with op.batch_alter_table("span", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_span_trace_id"))
        batch_op.drop_index(batch_op.f("ix_span_parent_span_id"))

    op.drop_table("span")
    op.drop_table("scenes_to_characters")
    with op.batch_alter_table("flow_version_deployment_attachment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_flow_version_deployment_attachment_user_id"))
        batch_op.drop_index(batch_op.f("ix_flow_version_deployment_attachment_provider_snapshot_id"))
        batch_op.drop_index(batch_op.f("ix_flow_version_deployment_attachment_flow_version_id"))
        batch_op.drop_index(batch_op.f("ix_flow_version_deployment_attachment_deployment_id"))

    op.drop_table("flow_version_deployment_attachment")
    with op.batch_alter_table("asset_entries", schema=None) as batch_op:
        batch_op.drop_index("idx_unq_scene_asset")
        batch_op.drop_index(
            "idx_unq_project_asset",
            postgresql_where=sa.text(
                "scene_id IS NULL AND character_id IS NULL AND location_id IS NULL AND file_id IS NULL"
            ),
        )
        batch_op.drop_index("idx_unq_loc_asset")
        batch_op.drop_index("idx_unq_file_asset")
        batch_op.drop_index("idx_unq_char_asset")
        batch_op.drop_index("idx_asset_entries_scene")
        batch_op.drop_index("idx_asset_entries_project")
        batch_op.drop_index("idx_asset_entries_location")
        batch_op.drop_index("idx_asset_entries_file")
        batch_op.drop_index("idx_asset_entries_character")

    op.drop_table("asset_entries")
    with op.batch_alter_table("trace", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_trace_session_id"))
        batch_op.drop_index(batch_op.f("ix_trace_flow_id"))

    op.drop_table("trace")
    with op.batch_alter_table("tag_registry", schema=None) as batch_op:
        batch_op.drop_index("idx_tag_scope")
        batch_op.drop_index("idx_tag_handle_fuzzy", postgresql_using="gin", postgresql_ops={"handle": "gin_trgm_ops"})

    op.drop_table("tag_registry")
    with op.batch_alter_table("scenes", schema=None) as batch_op:
        batch_op.drop_index("scenes_guidance_idx")

    op.drop_table("scenes")
    with op.batch_alter_table("flow_version", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_flow_version_user_id"))
        batch_op.drop_index(batch_op.f("ix_flow_version_flow_id"))
        batch_op.drop_index(batch_op.f("ix_flow_version_created_at"))

    op.drop_table("flow_version")
    op.drop_table("props")
    op.drop_table("lore")
    with op.batch_alter_table("locations", schema=None) as batch_op:
        batch_op.drop_index("locations_guidance_idx")

    op.drop_table("locations")
    with op.batch_alter_table("flow", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_flow_user_id"))
        batch_op.drop_index(batch_op.f("ix_flow_name"))
        batch_op.drop_index(batch_op.f("ix_flow_folder_id"))
        batch_op.drop_index(batch_op.f("ix_flow_endpoint_name"))
        batch_op.drop_index(batch_op.f("ix_flow_description"))

    op.drop_table("flow")
    with op.batch_alter_table("file", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_file_folder_id"))

    op.drop_table("file")
    with op.batch_alter_table("deployment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_deployment_user_id"))
        batch_op.drop_index(batch_op.f("ix_deployment_resource_key"))
        batch_op.drop_index(batch_op.f("ix_deployment_project_id"))
        batch_op.drop_index(batch_op.f("ix_deployment_name"))
        batch_op.drop_index(batch_op.f("ix_deployment_deployment_type"))
        batch_op.drop_index(batch_op.f("ix_deployment_deployment_provider_account_id"))

    op.drop_table("deployment")
    with op.batch_alter_table("characters", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_characters_name"))
        batch_op.drop_index("characters_guidance_idx")

    op.drop_table("characters")
    with op.batch_alter_table("blocks", schema=None) as batch_op:
        batch_op.drop_index("idx_blocks_search", postgresql_using="gin")
        batch_op.drop_index("idx_blocks_project_id")

    op.drop_table("blocks")
    op.drop_table("variable")
    with op.batch_alter_table("users_to_teams", schema=None) as batch_op:
        batch_op.drop_index("ix_users_to_teams_user_id")
        batch_op.drop_index("ix_users_to_teams_team_id")

    op.drop_table("users_to_teams")
    with op.batch_alter_table("sso_user_profile", schema=None) as batch_op:
        batch_op.drop_index("uq_sso_user_profile_provider_user")
        batch_op.drop_index(batch_op.f("ix_sso_user_profile_user_id"))
        batch_op.drop_index(batch_op.f("ix_sso_user_profile_email"))

    op.drop_table("sso_user_profile")
    op.drop_table("sso_config")
    with op.batch_alter_table("folder", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_folder_name"))

    op.drop_table("folder")
    with op.batch_alter_table("deployment_provider_account", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_deployment_provider_account_user_id"))
        batch_op.drop_index(batch_op.f("ix_deployment_provider_account_provider_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_deployment_provider_account_provider_key"))

    op.drop_table("deployment_provider_account")
    with op.batch_alter_table("apikey", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_apikey_user_id"))
        batch_op.drop_index(batch_op.f("ix_apikey_name"))
        batch_op.drop_index(batch_op.f("ix_apikey_api_key_hash"))
        batch_op.drop_index(batch_op.f("ix_apikey_api_key"))

    op.drop_table("apikey")
    with op.batch_alter_table("user_credit", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_credit_user_id"))

    op.drop_table("user_credit")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_username"))

    op.drop_table("user")
    op.drop_table("transaction")
    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_teams_name"))

    op.drop_table("teams")
    with op.batch_alter_table("stripeproduct", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_stripeproduct_tier"))
        batch_op.drop_index(batch_op.f("ix_stripeproduct_stripe_product_id"))
        batch_op.drop_index(batch_op.f("ix_stripeproduct_stripe_price_id"))

    op.drop_table("stripeproduct")
    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notification_user_id"))

    op.drop_table("notification")
    op.drop_table("message")
    op.drop_table("media_objects")
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_job_user_id"))
        batch_op.drop_index(batch_op.f("ix_job_type"))
        batch_op.drop_index(batch_op.f("ix_job_job_id"))
        batch_op.drop_index(batch_op.f("ix_job_flow_id"))
        batch_op.drop_index(batch_op.f("ix_job_asset_id"))

    op.drop_table("job")
    with op.batch_alter_table("feature_gate", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_feature_gate_tier"))
        batch_op.drop_index(batch_op.f("ix_feature_gate_feature"))

    op.drop_table("feature_gate")
    with op.batch_alter_table("credit_transaction", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_credit_transaction_user_id"))

    op.drop_table("credit_transaction")
    # ### end Alembic commands ###
