"""sync models

Phase: EXPAND

Revision ID: 0e9c4b77e935  # pragma: allowlist secret
Revises: a494819d83fe  # pragma: allowlist secret
Create Date: 2026-06-17 16:20:22.471692

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "0e9c4b77e935"  # pragma: allowlist secret
down_revision: str | None = "a494819d83fe"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scenes",
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("scene_index", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("start_time", sa.Float(), nullable=False),
        sa.Column("end_time", sa.Float(), nullable=False),
        sa.Column("duration", sa.Float(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("lyrics", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("musical_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("music_change", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("intensity", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("mood", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tempo", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("audio_evidence", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("transient_impact", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("audio_sync", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("transition_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("shot_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("camera_angle", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("camera_movement", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("composition", sa.JSON(), nullable=False),
        sa.Column("lighting", sa.JSON(), nullable=False),
        sa.Column("continuity_notes", sa.JSON(), nullable=False),
        sa.Column("character_reference_ids", sa.JSON(), nullable=False),
        sa.Column("location_reference_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("progress_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("guidance_level", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"]),
        sa.ForeignKeyConstraint(["project_id"], ["folder.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    with op.batch_alter_table("scenes", schema=None) as batch_op:
        batch_op.create_index("scenes_guidance_idx", ["guidance_level"], unique=False)

    with op.batch_alter_table("vertex_build", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_vertex_build_job_id"))

    op.drop_table("vertex_build")
    with op.batch_alter_table("characters", schema=None) as batch_op:
        batch_op.alter_column("aliases", existing_type=sa.VARCHAR(), type_=sa.JSON(), existing_nullable=False)

    with op.batch_alter_table("file", schema=None) as batch_op:
        batch_op.add_column(sa.Column("folder_id", sa.Uuid(), nullable=True))
        batch_op.drop_constraint(batch_op.f("file_name_user_id_key"), type_="unique")
        batch_op.create_index(batch_op.f("ix_file_folder_id"), ["folder_id"], unique=False)
        batch_op.create_unique_constraint(None, ["name", "user_id", "folder_id"])
        batch_op.create_foreign_key(None, "folder", ["folder_id"], ["id"], ondelete="CASCADE")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("file", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_index(batch_op.f("ix_file_folder_id"))
        batch_op.create_unique_constraint(batch_op.f("file_name_user_id_key"), ["name", "user_id"])
        batch_op.drop_column("folder_id")

    with op.batch_alter_table("characters", schema=None) as batch_op:
        batch_op.alter_column("aliases", existing_type=sa.JSON(), type_=sa.VARCHAR(), existing_nullable=False)

    op.create_table(
        "vertex_build",
        sa.Column("timestamp", sa.DATETIME(), nullable=False),
        sa.Column("id", sa.VARCHAR(), nullable=False),
        sa.Column("data", sqlite.JSON(), nullable=True),
        sa.Column("artifacts", sqlite.JSON(), nullable=True),
        sa.Column("params", sa.TEXT(), nullable=True),
        sa.Column("build_id", sa.CHAR(length=32), nullable=False),
        sa.Column("flow_id", sa.CHAR(length=32), nullable=False),
        sa.Column("valid", sa.BOOLEAN(), nullable=False),
        sa.Column("job_id", sa.CHAR(length=32), nullable=True),
        sa.PrimaryKeyConstraint("build_id", name=op.f("pk_vertex_build")),
    )
    with op.batch_alter_table("vertex_build", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_vertex_build_job_id"), ["job_id"], unique=False)

    with op.batch_alter_table("scenes", schema=None) as batch_op:
        batch_op.drop_index("scenes_guidance_idx")

    op.drop_table("scenes")
    # ### end Alembic commands ###
