"""Phase: EXPAND

Revision ID: 209dea0782a0
Revises: 9f0da6f29b56
Create Date: 2026-07-06 04:19:04.671518

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "209dea0782a0"  # pragma: allowlist secret
down_revision: str | None = "9f0da6f29b56"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nap_repository", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "tag",
                sqlmodel.sql.sqltypes.AutoString(),
                nullable=False,
                server_default="main",
            )
        )
        batch_op.add_column(sa.Column("pinned_commit_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    op.alter_column(
        "nap_repository",
        "tag",
        server_default=None,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nap_repository", schema=None) as batch_op:
        batch_op.drop_column("pinned_commit_hash")
        batch_op.drop_column("tag")

    # ### end Alembic commands ###
