"""Create project_repository_link join table for many-to-one repos

Phase: EXPAND

Revision ID: 3100d8458a54
Revises: 209dea0782a0
Create Date: 2026-07-06 04:45:51.201020

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3100d8458a54"  # pragma: allowlist secret
down_revision: str | None = "209dea0782a0"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_repository_link",
        sa.Column("folder_id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("tag", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("pinned_commit_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(["folder_id"], ["folder.id"]),
        sa.ForeignKeyConstraint(["repository_id"], ["nap_repository.id"]),
        sa.PrimaryKeyConstraint("folder_id", "repository_id"),
    )

    # Migrate existing data: copy each nap_repository row into a link
    conn.execute(
        sa.text("""
            INSERT INTO project_repository_link (folder_id, repository_id, tag, pinned_commit_hash)
            SELECT folder_id, id, tag, pinned_commit_hash
            FROM nap_repository
            WHERE folder_id IS NOT NULL
        """)
    )

    with op.batch_alter_table("nap_repository", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_nap_repository_folder_id_folder"), type_="foreignkey")
        batch_op.drop_column("folder_id")
        batch_op.drop_column("tag")
        batch_op.drop_column("pinned_commit_hash")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nap_repository", schema=None) as batch_op:
        batch_op.add_column(sa.Column("pinned_commit_hash", sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column("tag", sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column("folder_id", sa.UUID(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f("fk_nap_repository_folder_id_folder"), "folder", ["folder_id"], ["id"])

    op.drop_table("project_repository_link")
    # ### end Alembic commands ###
