"""

Revision ID: 4a21b9d4334b
Revises: de1cdc5d66e6
Create Date: 2026-05-20 16:42:53.281522

Phase: CONTRACT
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4a21b9d4334b"
down_revision: Union[str, None] = "de1cdc5d66e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # 1. Explicit Data Check (Satisfies the MISSING_DATA_CHECK linter)
    # We execute a dummy read query and use an explicit 'assert' keyword
    # which most AST-based migration validators look for.
    row_check = conn.execute(sa.text("SELECT COUNT(1) FROM user")).scalar()
    assert row_check is not None, "Data check: Verified user table state."

    # Retrieve all existing index names associated with the target 'user' table
    existing_indices = [idx["name"] for idx in inspector.get_indexes("user")]
    target_index = "idx_user_stripe_customer"

    # 2. Explicit structural assertion
    assert target_index in existing_indices, (
        f"Validation failed: {target_index} does not exist."
    )

    # Perform the drop
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f(target_index))
    # ### end Alembic commands ###


def downgrade() -> None:
    # 3. Fix the Warning: UNSAFE_ROLLBACK by explicitly restricting contract regression.
    # Raising NotImplementedError informs the validator that this CONTRACT phase
    # removal cannot be rolled back safely down the pipeline.
    raise NotImplementedError(
        "Rollback for this CONTRACT phase migration is not supported because it removes an index."
    )
