"""

Revision ID: 4a21b9d4334b
Revises: de1cdc5d66e6
Create Date: 2026-05-20 16:42:53.281522

Phase: CONTRACT
"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4a21b9d4334b"
down_revision: Union[str, None] = "de1cdc5d66e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_user_stripe_customer"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("idx_user_stripe_customer"), ["stripe_customer_id"], unique=False
        )

    # ### end Alembic commands ###
