"""sync models with database

Phase: EXPAND

Revision ID: 95d2ec932a09
Revises: 8311396122a7
Create Date: 2026-07-04 02:10:56.789683

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "95d2ec932a09"  # pragma: allowlist secret
down_revision: str | None = "8311396122a7"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    conn = op.get_bind()  # noqa: F841
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("apikey", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["id"])

    with op.batch_alter_table("asset_entries", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["id"])

    with op.batch_alter_table("asset_versions", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["id"])

    with op.batch_alter_table("blocks", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["id"])

    with op.batch_alter_table("characters", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["id"])

    with op.batch_alter_table("credential", schema=None) as batch_op:
        batch_op.alter_column(
            "provider",
            existing_type=sa.VARCHAR(),
            comment=None,
            existing_comment="Provider name, e.g. 'OpenAI'",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "api_key",
            existing_type=sa.VARCHAR(),
            comment=None,
            existing_comment="Encrypted managed API key",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            comment=None,
            existing_comment="When this credential was first stored",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "updated_at",
            existing_type=postgresql.TIMESTAMP(),
            comment=None,
            existing_comment="When this credential was last updated",
            existing_nullable=False,
        )

    with op.batch_alter_table("flow", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["id"])

    with op.batch_alter_table("locations", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["id"])

    with op.batch_alter_table("lore", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["id"])

    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.create_index(
            "ix_message_session_metadata_tenant",
            [sa.literal_column("(session_metadata->>'tenant_id')")],
            unique=False,
            postgresql_using="btree",
        )
        batch_op.create_index(
            "ix_message_session_metadata_user",
            [sa.literal_column("(session_metadata->>'user_id')")],
            unique=False,
            postgresql_using="btree",
        )

    with op.batch_alter_table("props", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["id"])

    with op.batch_alter_table("scenes", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["id"])

    # NOTE: scenes_to_characters.scene_id and character_id are part of a
    # composite primary key — they cannot be made nullable. The autogenerator
    # incorrectly detected a nullable change here. Skipping.
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()  # noqa: F841
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    # NOTE: scenes_to_characters changes were skipped in upgrade — no downgrade needed.
    with op.batch_alter_table("scenes", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    with op.batch_alter_table("props", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.drop_index("ix_message_session_metadata_user", postgresql_using="btree")
        batch_op.drop_index("ix_message_session_metadata_tenant", postgresql_using="btree")

    with op.batch_alter_table("lore", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    with op.batch_alter_table("locations", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    with op.batch_alter_table("flow", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    with op.batch_alter_table("credential", schema=None) as batch_op:
        batch_op.alter_column(
            "updated_at",
            existing_type=postgresql.TIMESTAMP(),
            comment="When this credential was last updated",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            comment="When this credential was first stored",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "api_key", existing_type=sa.VARCHAR(), comment="Encrypted managed API key", existing_nullable=False
        )
        batch_op.alter_column(
            "provider", existing_type=sa.VARCHAR(), comment="Provider name, e.g. 'OpenAI'", existing_nullable=False
        )

    with op.batch_alter_table("characters", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    with op.batch_alter_table("blocks", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    with op.batch_alter_table("asset_versions", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    with op.batch_alter_table("asset_entries", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    with op.batch_alter_table("apikey", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    # ### end Alembic commands ###
