"""Remove unique constraint on NapRepository.folder_id

Phase: EXPAND

Revision ID: 9f0da6f29b56
Revises: a1b2c3d4e5f6
Create Date: 2026-07-05 13:04:52.037354

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9f0da6f29b56"  # pragma: allowlist secret
down_revision: str | None = "a1b2c3d4e5f6"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nap_repository", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.VARCHAR(), type_=sa.Uuid(), postgresql_using="id::uuid", existing_nullable=False
        )
        batch_op.drop_constraint(batch_op.f("uq_nap_repository_folder_id"), type_="unique")
        batch_op.create_unique_constraint(None, ["id"])
        batch_op.drop_constraint(batch_op.f("fk_nap_repository_folder_id_folder"), type_="foreignkey")
        batch_op.create_foreign_key(None, "folder", ["folder_id"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nap_repository", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_nap_repository_folder_id_folder"), "folder", ["folder_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.drop_constraint(None, type_="unique")
        batch_op.create_unique_constraint(
            batch_op.f("uq_nap_repository_folder_id"), ["folder_id"], postgresql_nulls_not_distinct=False
        )
        batch_op.alter_column("id", existing_type=sa.Uuid(), type_=sa.VARCHAR(), existing_nullable=False)

    # ### end Alembic commands ###
