"""Auto-generated migration: stripeproduct table cleanup.

Revision ID: a07a6552c8cf
Revises: 7db1179f2119
Create Date: 2026-06-13 17:25:52.073235

Phase: EXPAND
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "a07a6552c8cf"  # pragma: allowlist secret
down_revision: str | None = "7db1179f2119"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    conn = op.get_bind()

    # Ensure any null data is backfilled with a current timestamp
    op.execute(
        """
        UPDATE feature_gate
        SET created_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
        WHERE created_at IS NULL OR updated_at IS NULL
        """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stripeproduct",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("stripe_product_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("stripe_price_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tier", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("product_credits", sa.Integer(), nullable=True),
        sa.Column("unit_amount", sa.Integer(), nullable=True),
        sa.Column("currency", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("product_metadata", sa.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("stripeproduct", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_stripeproduct_stripe_price_id"), ["stripe_price_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_stripeproduct_stripe_product_id"), ["stripe_product_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_stripeproduct_tier"), ["tier"], unique=False)

    with op.batch_alter_table("pending_job", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pending_job_user_id"))

    op.drop_table("pending_job")
    with op.batch_alter_table("stripe_product", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_stripe_product_stripe_price_id"))
        batch_op.drop_index(batch_op.f("ix_stripe_product_stripe_product_id"))
        batch_op.drop_index(batch_op.f("ix_stripe_product_tier"))

    op.drop_table("stripe_product")
    with op.batch_alter_table("asset_entries", schema=None) as batch_op:
        batch_op.alter_column(
            "asset_key", existing_type=sa.TEXT(), type_=sqlmodel.sql.sqltypes.AutoString(), existing_nullable=False
        )
        batch_op.alter_column("created_at", existing_type=sa.DATETIME(), nullable=True)
        batch_op.alter_column("updated_at", existing_type=sa.DATETIME(), nullable=True)
        batch_op.create_unique_constraint(None, ["id"])
        batch_op.drop_constraint(batch_op.f("fk_asset_entries_project_id_folder"), type_="foreignkey")
        batch_op.create_foreign_key(None, "folder", ["project_id"], ["id"])

    with op.batch_alter_table("asset_versions", schema=None) as batch_op:
        batch_op.alter_column(
            "data", existing_type=sa.TEXT(), type_=sqlmodel.sql.sqltypes.AutoString(), existing_nullable=False
        )
        batch_op.alter_column(
            "media_id", existing_type=sa.TEXT(), type_=sqlmodel.sql.sqltypes.AutoString(), existing_nullable=True
        )
        batch_op.alter_column(
            "type", existing_type=sa.TEXT(), type_=sqlmodel.sql.sqltypes.AutoString(), existing_nullable=False
        )
        batch_op.alter_column("started_at", existing_type=sa.DATETIME(), nullable=True)
        batch_op.alter_column("created_at", existing_type=sa.DATETIME(), nullable=True)
        batch_op.create_unique_constraint(None, ["id"])
        batch_op.drop_constraint(batch_op.f("fk_asset_versions_asset_entry_id_asset_entries"), type_="foreignkey")
        batch_op.drop_constraint(batch_op.f("fk_asset_versions_media_id_media_objects"), type_="foreignkey")
        batch_op.create_foreign_key(None, "media_objects", ["media_id"], ["data"])
        batch_op.create_foreign_key(None, "asset_entries", ["asset_entry_id"], ["id"])

    with op.batch_alter_table("blocks", schema=None) as batch_op:
        batch_op.alter_column(
            "title", existing_type=sa.TEXT(), type_=sqlmodel.sql.sqltypes.AutoString(), existing_nullable=True
        )
        batch_op.alter_column(
            "content", existing_type=sa.TEXT(), type_=sqlmodel.sql.sqltypes.AutoString(), existing_nullable=False
        )
        batch_op.alter_column(
            "dialogue", existing_type=sa.TEXT(), type_=sqlmodel.sql.sqltypes.AutoString(), existing_nullable=True
        )
        batch_op.alter_column(
            "image_url", existing_type=sa.TEXT(), type_=sqlmodel.sql.sqltypes.AutoString(), existing_nullable=True
        )
        batch_op.create_unique_constraint(None, ["id"])
        batch_op.drop_constraint(batch_op.f("fk_blocks_project_id_folder"), type_="foreignkey")
        batch_op.create_foreign_key(None, "folder", ["project_id"], ["id"])

    with op.batch_alter_table("characters", schema=None) as batch_op:
        batch_op.alter_column(
            "reference_id", existing_type=sa.TEXT(), type_=sqlmodel.sql.sqltypes.AutoString(), existing_nullable=False
        )
        batch_op.alter_column(
            "name", existing_type=sa.TEXT(), type_=sqlmodel.sql.sqltypes.AutoString(), existing_nullable=False
        )
        batch_op.create_unique_constraint(None, ["id"])
        batch_op.drop_constraint(batch_op.f("fk_characters_project_id_folder"), type_="foreignkey")
        batch_op.create_foreign_key(None, "folder", ["project_id"], ["id"])

    with op.batch_alter_table("credit_transaction", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=sa.DATETIME(), nullable=False)
        batch_op.drop_index(batch_op.f("idx_credit_transaction_user_reason"))

    with op.batch_alter_table("feature_gate", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=sa.DATETIME(), nullable=False)
        batch_op.alter_column("updated_at", existing_type=sa.DATETIME(), nullable=False)

    with op.batch_alter_table("folder", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.TEXT(),
            type_=sqlmodel.sql.sqltypes.AutoString(),
            existing_nullable=False,
            existing_server_default=sa.text("'pending'"),
        )

    with op.batch_alter_table("locations", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=sa.DATETIME(), nullable=True)
        batch_op.alter_column("updated_at", existing_type=sa.DATETIME(), nullable=True)
        batch_op.alter_column(
            "reference_id", existing_type=sa.TEXT(), type_=sqlmodel.sql.sqltypes.AutoString(), existing_nullable=False
        )
        batch_op.alter_column(
            "name", existing_type=sa.TEXT(), type_=sqlmodel.sql.sqltypes.AutoString(), existing_nullable=False
        )
        batch_op.alter_column(
            "type", existing_type=sa.TEXT(), type_=sqlmodel.sql.sqltypes.AutoString(), existing_nullable=False
        )
        batch_op.alter_column(
            "mood", existing_type=sa.TEXT(), type_=sqlmodel.sql.sqltypes.AutoString(), existing_nullable=False
        )
        batch_op.alter_column(
            "time_of_day", existing_type=sa.TEXT(), type_=sqlmodel.sql.sqltypes.AutoString(), existing_nullable=False
        )
        batch_op.alter_column(
            "weather", existing_type=sa.TEXT(), type_=sqlmodel.sql.sqltypes.AutoString(), existing_nullable=False
        )
        batch_op.alter_column(
            "ground_surface", existing_type=sa.TEXT(), type_=sqlmodel.sql.sqltypes.AutoString(), existing_nullable=False
        )
        batch_op.alter_column(
            "sky_or_ceiling", existing_type=sa.TEXT(), type_=sqlmodel.sql.sqltypes.AutoString(), existing_nullable=False
        )
        batch_op.create_unique_constraint(None, ["id"])
        batch_op.drop_constraint(batch_op.f("fk_locations_project_id_folder"), type_="foreignkey")
        batch_op.create_foreign_key(None, "folder", ["project_id"], ["id"])

    with op.batch_alter_table("lore", schema=None) as batch_op:
        batch_op.alter_column(
            "content", existing_type=sa.TEXT(), type_=sqlmodel.sql.sqltypes.AutoString(), existing_nullable=False
        )
        batch_op.create_unique_constraint(None, ["id"])
        batch_op.drop_constraint(batch_op.f("fk_lore_project_id_folder"), type_="foreignkey")
        batch_op.create_foreign_key(None, "folder", ["project_id"], ["id"])

    with op.batch_alter_table("media_objects", schema=None) as batch_op:
        batch_op.alter_column(
            "data", existing_type=sa.TEXT(), type_=sqlmodel.sql.sqltypes.AutoString(), existing_nullable=False
        )
        batch_op.alter_column(
            "status",
            existing_type=sa.TEXT(),
            type_=sqlmodel.sql.sqltypes.AutoString(),
            existing_nullable=False,
            existing_server_default=sa.text("'active'"),
        )

    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=sa.DATETIME(), nullable=False)

    with op.batch_alter_table("props", schema=None) as batch_op:
        batch_op.alter_column(
            "reference_id", existing_type=sa.TEXT(), type_=sqlmodel.sql.sqltypes.AutoString(), existing_nullable=False
        )
        batch_op.alter_column(
            "name", existing_type=sa.TEXT(), type_=sqlmodel.sql.sqltypes.AutoString(), existing_nullable=False
        )
        batch_op.alter_column(
            "type", existing_type=sa.TEXT(), type_=sqlmodel.sql.sqltypes.AutoString(), existing_nullable=False
        )
        batch_op.alter_column("created_at", existing_type=sa.DATETIME(), nullable=True)
        batch_op.alter_column("updated_at", existing_type=sa.DATETIME(), nullable=True)
        batch_op.create_unique_constraint(None, ["id"])

    with op.batch_alter_table("scenes", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=sa.DATETIME(), nullable=True)
        batch_op.alter_column("updated_at", existing_type=sa.DATETIME(), nullable=True)
        batch_op.alter_column(
            "name", existing_type=sa.TEXT(), type_=sqlmodel.sql.sqltypes.AutoString(), existing_nullable=False
        )
        batch_op.alter_column(
            "type", existing_type=sa.TEXT(), type_=sqlmodel.sql.sqltypes.AutoString(), existing_nullable=False
        )
        batch_op.alter_column(
            "lyrics", existing_type=sa.TEXT(), type_=sqlmodel.sql.sqltypes.AutoString(), existing_nullable=True
        )
        batch_op.alter_column(
            "musical_description",
            existing_type=sa.TEXT(),
            type_=sqlmodel.sql.sqltypes.AutoString(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "music_change", existing_type=sa.TEXT(), type_=sqlmodel.sql.sqltypes.AutoString(), existing_nullable=True
        )
        batch_op.alter_column(
            "intensity", existing_type=sa.TEXT(), type_=sqlmodel.sql.sqltypes.AutoString(), existing_nullable=True
        )
        batch_op.alter_column(
            "mood", existing_type=sa.TEXT(), type_=sqlmodel.sql.sqltypes.AutoString(), existing_nullable=False
        )
        batch_op.alter_column(
            "tempo", existing_type=sa.TEXT(), type_=sqlmodel.sql.sqltypes.AutoString(), existing_nullable=False
        )
        batch_op.alter_column(
            "audio_evidence", existing_type=sa.TEXT(), type_=sqlmodel.sql.sqltypes.AutoString(), existing_nullable=False
        )
        batch_op.alter_column(
            "transient_impact",
            existing_type=sa.TEXT(),
            type_=sqlmodel.sql.sqltypes.AutoString(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "audio_sync", existing_type=sa.TEXT(), type_=sqlmodel.sql.sqltypes.AutoString(), existing_nullable=False
        )
        batch_op.alter_column(
            "transition_type",
            existing_type=sa.TEXT(),
            type_=sqlmodel.sql.sqltypes.AutoString(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "shot_type", existing_type=sa.TEXT(), type_=sqlmodel.sql.sqltypes.AutoString(), existing_nullable=False
        )
        batch_op.alter_column(
            "camera_angle", existing_type=sa.TEXT(), type_=sqlmodel.sql.sqltypes.AutoString(), existing_nullable=False
        )
        batch_op.alter_column(
            "camera_movement",
            existing_type=sa.TEXT(),
            type_=sqlmodel.sql.sqltypes.AutoString(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "location_reference_id",
            existing_type=sa.TEXT(),
            type_=sqlmodel.sql.sqltypes.AutoString(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "status",
            existing_type=sa.TEXT(),
            type_=sqlmodel.sql.sqltypes.AutoString(),
            existing_nullable=False,
            existing_server_default=sa.text("'pending'"),
        )
        batch_op.alter_column(
            "progress_message",
            existing_type=sa.TEXT(),
            type_=sqlmodel.sql.sqltypes.AutoString(),
            existing_nullable=True,
        )
        batch_op.create_unique_constraint(None, ["id"])
        batch_op.drop_constraint(batch_op.f("fk_scenes_location_id_locations"), type_="foreignkey")
        batch_op.drop_constraint(batch_op.f("fk_scenes_project_id_folder"), type_="foreignkey")
        batch_op.create_foreign_key(None, "folder", ["project_id"], ["id"])
        batch_op.create_foreign_key(None, "locations", ["location_id"], ["id"])

    with op.batch_alter_table("scenes_to_characters", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_scenes_to_characters_scene_id_scenes"), type_="foreignkey")
        batch_op.drop_constraint(batch_op.f("fk_scenes_to_characters_character_id_characters"), type_="foreignkey")
        batch_op.create_foreign_key(None, "scenes", ["scene_id"], ["id"])
        batch_op.create_foreign_key(None, "characters", ["character_id"], ["id"])

    with op.batch_alter_table("tag_registry", schema=None) as batch_op:
        batch_op.alter_column(
            "handle", existing_type=sa.TEXT(), type_=sqlmodel.sql.sqltypes.AutoString(), existing_nullable=False
        )
        batch_op.alter_column(
            "entity_type", existing_type=sa.TEXT(), type_=sqlmodel.sql.sqltypes.AutoString(), existing_nullable=False
        )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_user_stripe_customer"))

    with op.batch_alter_table("user_credit", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=sa.DATETIME(), nullable=False)
        batch_op.alter_column("updated_at", existing_type=sa.DATETIME(), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_credit", schema=None) as batch_op:
        batch_op.alter_column("updated_at", existing_type=sa.DATETIME(), nullable=True)
        batch_op.alter_column("created_at", existing_type=sa.DATETIME(), nullable=True)

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("idx_user_stripe_customer"), ["stripe_customer_id"], unique=False)

    with op.batch_alter_table("tag_registry", schema=None) as batch_op:
        batch_op.alter_column(
            "entity_type", existing_type=sqlmodel.sql.sqltypes.AutoString(), type_=sa.TEXT(), existing_nullable=False
        )
        batch_op.alter_column(
            "handle", existing_type=sqlmodel.sql.sqltypes.AutoString(), type_=sa.TEXT(), existing_nullable=False
        )

    with op.batch_alter_table("scenes_to_characters", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_scenes_to_characters_character_id_characters"),
            "characters",
            ["character_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_scenes_to_characters_scene_id_scenes"), "scenes", ["scene_id"], ["id"], ondelete="SET NULL"
        )

    with op.batch_alter_table("scenes", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_scenes_project_id_folder"), "folder", ["project_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_scenes_location_id_locations"), "locations", ["location_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.drop_constraint(None, type_="unique")
        batch_op.alter_column(
            "progress_message",
            existing_type=sqlmodel.sql.sqltypes.AutoString(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "status",
            existing_type=sqlmodel.sql.sqltypes.AutoString(),
            type_=sa.TEXT(),
            existing_nullable=False,
            existing_server_default=sa.text("'pending'"),
        )
        batch_op.alter_column(
            "location_reference_id",
            existing_type=sqlmodel.sql.sqltypes.AutoString(),
            type_=sa.TEXT(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "camera_movement",
            existing_type=sqlmodel.sql.sqltypes.AutoString(),
            type_=sa.TEXT(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "camera_angle", existing_type=sqlmodel.sql.sqltypes.AutoString(), type_=sa.TEXT(), existing_nullable=False
        )
        batch_op.alter_column(
            "shot_type", existing_type=sqlmodel.sql.sqltypes.AutoString(), type_=sa.TEXT(), existing_nullable=False
        )
        batch_op.alter_column(
            "transition_type",
            existing_type=sqlmodel.sql.sqltypes.AutoString(),
            type_=sa.TEXT(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "audio_sync", existing_type=sqlmodel.sql.sqltypes.AutoString(), type_=sa.TEXT(), existing_nullable=False
        )
        batch_op.alter_column(
            "transient_impact",
            existing_type=sqlmodel.sql.sqltypes.AutoString(),
            type_=sa.TEXT(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "audio_evidence", existing_type=sqlmodel.sql.sqltypes.AutoString(), type_=sa.TEXT(), existing_nullable=False
        )
        batch_op.alter_column(
            "tempo", existing_type=sqlmodel.sql.sqltypes.AutoString(), type_=sa.TEXT(), existing_nullable=False
        )
        batch_op.alter_column(
            "mood", existing_type=sqlmodel.sql.sqltypes.AutoString(), type_=sa.TEXT(), existing_nullable=False
        )
        batch_op.alter_column(
            "intensity", existing_type=sqlmodel.sql.sqltypes.AutoString(), type_=sa.TEXT(), existing_nullable=True
        )
        batch_op.alter_column(
            "music_change", existing_type=sqlmodel.sql.sqltypes.AutoString(), type_=sa.TEXT(), existing_nullable=True
        )
        batch_op.alter_column(
            "musical_description",
            existing_type=sqlmodel.sql.sqltypes.AutoString(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "lyrics", existing_type=sqlmodel.sql.sqltypes.AutoString(), type_=sa.TEXT(), existing_nullable=True
        )
        batch_op.alter_column(
            "type", existing_type=sqlmodel.sql.sqltypes.AutoString(), type_=sa.TEXT(), existing_nullable=False
        )
        batch_op.alter_column(
            "name", existing_type=sqlmodel.sql.sqltypes.AutoString(), type_=sa.TEXT(), existing_nullable=False
        )
        batch_op.alter_column("updated_at", existing_type=sa.DATETIME(), nullable=False)
        batch_op.alter_column("created_at", existing_type=sa.DATETIME(), nullable=False)

    with op.batch_alter_table("props", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.alter_column("updated_at", existing_type=sa.DATETIME(), nullable=False)
        batch_op.alter_column("created_at", existing_type=sa.DATETIME(), nullable=False)
        batch_op.alter_column(
            "type", existing_type=sqlmodel.sql.sqltypes.AutoString(), type_=sa.TEXT(), existing_nullable=False
        )
        batch_op.alter_column(
            "name", existing_type=sqlmodel.sql.sqltypes.AutoString(), type_=sa.TEXT(), existing_nullable=False
        )
        batch_op.alter_column(
            "reference_id", existing_type=sqlmodel.sql.sqltypes.AutoString(), type_=sa.TEXT(), existing_nullable=False
        )

    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=sa.DATETIME(), nullable=True)

    with op.batch_alter_table("media_objects", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sqlmodel.sql.sqltypes.AutoString(),
            type_=sa.TEXT(),
            existing_nullable=False,
            existing_server_default=sa.text("'active'"),
        )
        batch_op.alter_column(
            "data", existing_type=sqlmodel.sql.sqltypes.AutoString(), type_=sa.TEXT(), existing_nullable=False
        )

    with op.batch_alter_table("lore", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_lore_project_id_folder"), "folder", ["project_id"], ["id"], onupdate="CASCADE"
        )
        batch_op.drop_constraint(None, type_="unique")
        batch_op.alter_column(
            "content", existing_type=sqlmodel.sql.sqltypes.AutoString(), type_=sa.TEXT(), existing_nullable=False
        )

    with op.batch_alter_table("locations", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_locations_project_id_folder"), "folder", ["project_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.drop_constraint(None, type_="unique")
        batch_op.alter_column(
            "sky_or_ceiling", existing_type=sqlmodel.sql.sqltypes.AutoString(), type_=sa.TEXT(), existing_nullable=False
        )
        batch_op.alter_column(
            "ground_surface", existing_type=sqlmodel.sql.sqltypes.AutoString(), type_=sa.TEXT(), existing_nullable=False
        )
        batch_op.alter_column(
            "weather", existing_type=sqlmodel.sql.sqltypes.AutoString(), type_=sa.TEXT(), existing_nullable=False
        )
        batch_op.alter_column(
            "time_of_day", existing_type=sqlmodel.sql.sqltypes.AutoString(), type_=sa.TEXT(), existing_nullable=False
        )
        batch_op.alter_column(
            "mood", existing_type=sqlmodel.sql.sqltypes.AutoString(), type_=sa.TEXT(), existing_nullable=False
        )
        batch_op.alter_column(
            "type", existing_type=sqlmodel.sql.sqltypes.AutoString(), type_=sa.TEXT(), existing_nullable=False
        )
        batch_op.alter_column(
            "name", existing_type=sqlmodel.sql.sqltypes.AutoString(), type_=sa.TEXT(), existing_nullable=False
        )
        batch_op.alter_column(
            "reference_id", existing_type=sqlmodel.sql.sqltypes.AutoString(), type_=sa.TEXT(), existing_nullable=False
        )
        batch_op.alter_column("updated_at", existing_type=sa.DATETIME(), nullable=False)
        batch_op.alter_column("created_at", existing_type=sa.DATETIME(), nullable=False)

    with op.batch_alter_table("folder", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sqlmodel.sql.sqltypes.AutoString(),
            type_=sa.TEXT(),
            existing_nullable=False,
            existing_server_default=sa.text("'pending'"),
        )

    with op.batch_alter_table("feature_gate", schema=None) as batch_op:
        batch_op.alter_column("updated_at", existing_type=sa.DATETIME(), nullable=True)
        batch_op.alter_column("created_at", existing_type=sa.DATETIME(), nullable=True)

    with op.batch_alter_table("credit_transaction", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("idx_credit_transaction_user_reason"),
            ["user_id", "reason", "reference_type", "reference_id"],
            unique=False,
        )
        batch_op.alter_column("created_at", existing_type=sa.DATETIME(), nullable=True)

    with op.batch_alter_table("characters", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_characters_project_id_folder"), "folder", ["project_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.drop_constraint(None, type_="unique")
        batch_op.alter_column(
            "name", existing_type=sqlmodel.sql.sqltypes.AutoString(), type_=sa.TEXT(), existing_nullable=False
        )
        batch_op.alter_column(
            "reference_id", existing_type=sqlmodel.sql.sqltypes.AutoString(), type_=sa.TEXT(), existing_nullable=False
        )

    with op.batch_alter_table("blocks", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_blocks_project_id_folder"),
            "folder",
            ["project_id"],
            ["id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        )
        batch_op.drop_constraint(None, type_="unique")
        batch_op.alter_column(
            "image_url", existing_type=sqlmodel.sql.sqltypes.AutoString(), type_=sa.TEXT(), existing_nullable=True
        )
        batch_op.alter_column(
            "dialogue", existing_type=sqlmodel.sql.sqltypes.AutoString(), type_=sa.TEXT(), existing_nullable=True
        )
        batch_op.alter_column(
            "content", existing_type=sqlmodel.sql.sqltypes.AutoString(), type_=sa.TEXT(), existing_nullable=False
        )
        batch_op.alter_column(
            "title", existing_type=sqlmodel.sql.sqltypes.AutoString(), type_=sa.TEXT(), existing_nullable=True
        )

    with op.batch_alter_table("asset_versions", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_asset_versions_media_id_media_objects"),
            "media_objects",
            ["media_id"],
            ["data"],
            ondelete="RESTRICT",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_asset_versions_asset_entry_id_asset_entries"),
            "asset_entries",
            ["asset_entry_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_constraint(None, type_="unique")
        batch_op.alter_column("created_at", existing_type=sa.DATETIME(), nullable=False)
        batch_op.alter_column("started_at", existing_type=sa.DATETIME(), nullable=False)
        batch_op.alter_column(
            "type", existing_type=sqlmodel.sql.sqltypes.AutoString(), type_=sa.TEXT(), existing_nullable=False
        )
        batch_op.alter_column(
            "media_id", existing_type=sqlmodel.sql.sqltypes.AutoString(), type_=sa.TEXT(), existing_nullable=True
        )
        batch_op.alter_column(
            "data", existing_type=sqlmodel.sql.sqltypes.AutoString(), type_=sa.TEXT(), existing_nullable=False
        )

    with op.batch_alter_table("asset_entries", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_asset_entries_project_id_folder"), "folder", ["project_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.drop_constraint(None, type_="unique")
        batch_op.alter_column("updated_at", existing_type=sa.DATETIME(), nullable=False)
        batch_op.alter_column("created_at", existing_type=sa.DATETIME(), nullable=False)
        batch_op.alter_column(
            "asset_key", existing_type=sqlmodel.sql.sqltypes.AutoString(), type_=sa.TEXT(), existing_nullable=False
        )

    op.create_table(
        "stripe_product",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("stripe_product_id", sa.VARCHAR(), nullable=False),
        sa.Column("stripe_price_id", sa.VARCHAR(), nullable=False),
        sa.Column("name", sa.VARCHAR(), server_default=sa.text("('')"), nullable=False),
        sa.Column("description", sa.VARCHAR(), server_default=sa.text("('')"), nullable=False),
        sa.Column("tier", sa.VARCHAR(), nullable=True),
        sa.Column("type", sa.VARCHAR(), server_default=sa.text("'subscription'"), nullable=False),
        sa.Column("credits", sa.INTEGER(), nullable=True),
        sa.Column("unit_amount", sa.INTEGER(), nullable=True),
        sa.Column("currency", sa.VARCHAR(), server_default=sa.text("'USD'"), nullable=False),
        sa.Column("metadata", sqlite.JSON(), nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), server_default=sa.text("1"), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.Column("last_synced_at", sa.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stripe_product")),
    )
    with op.batch_alter_table("stripe_product", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_stripe_product_tier"), ["tier"], unique=False)
        batch_op.create_index(batch_op.f("ix_stripe_product_stripe_product_id"), ["stripe_product_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_stripe_product_stripe_price_id"), ["stripe_price_id"], unique=1)

    op.create_table(
        "pending_job",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.VARCHAR(), nullable=False),
        sa.Column("flow_id", sa.VARCHAR(), nullable=False),
        sa.Column("required_credits", sa.INTEGER(), nullable=False),
        sa.Column("reference_id", sa.VARCHAR(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pending_job")),
        sa.UniqueConstraint("user_id", "flow_id", name=op.f("uq_pending_job_user_flow")),
    )
    with op.batch_alter_table("pending_job", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pending_job_user_id"), ["user_id"], unique=False)

    with op.batch_alter_table("stripeproduct", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_stripeproduct_tier"))
        batch_op.drop_index(batch_op.f("ix_stripeproduct_stripe_product_id"))
        batch_op.drop_index(batch_op.f("ix_stripeproduct_stripe_price_id"))

    op.drop_table("stripeproduct")
    # ### end Alembic commands ###
