"""Folder-scoped files

Revision ID: a494819d83fe  # pragma: allowlist secret
Revises: 7b2c9f4a1d3e  # pragma: allowlist secret
Create Date: 2026-06-17 04:08:55.054302

Phase: EXPAND
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a494819d83fe"  # pragma: allowlist secret
down_revision: str | None = "7b2c9f4a1d3e"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("characters", schema=None) as batch_op:
        batch_op.alter_column("aliases", existing_type=sa.VARCHAR(), type_=sa.JSON(), existing_nullable=False)

    with op.batch_alter_table("scenes", schema=None) as batch_op:
        batch_op.alter_column("continuity_notes", existing_type=sa.VARCHAR(), type_=sa.JSON(), existing_nullable=False)
        batch_op.alter_column(
            "character_reference_ids", existing_type=sa.VARCHAR(), type_=sa.JSON(), existing_nullable=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scenes", schema=None) as batch_op:
        batch_op.alter_column(
            "character_reference_ids", existing_type=sa.JSON(), type_=sa.VARCHAR(), existing_nullable=False
        )
        batch_op.alter_column("continuity_notes", existing_type=sa.JSON(), type_=sa.VARCHAR(), existing_nullable=False)

    with op.batch_alter_table("characters", schema=None) as batch_op:
        batch_op.alter_column("aliases", existing_type=sa.JSON(), type_=sa.VARCHAR(), existing_nullable=False)

    # ### end Alembic commands ###
