"""Add missing scenes table.

Revision ID: ad3cacfcd132
Revises: 0020_add_canvas_tables
Create Date: 2026-05-30 00:21:04.990198

Phase: EXPAND
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ad3cacfcd132"
down_revision: str | None = "0020_add_canvas_tables"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # ### commands auto generated by Alembic - please adjust! ###
    if "scenes" not in inspector.get_table_names():
        op.create_table(
            "scenes",
            sa.Column("created_at", sa.DateTime(), nullable=True),
            sa.Column("updated_at", sa.DateTime(), nullable=True),
            sa.Column("project_id", sa.Uuid(), nullable=False),
            sa.Column("scene_index", sa.Integer(), nullable=False),
            sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("start_time", sa.Float(), nullable=False),
            sa.Column("end_time", sa.Float(), nullable=False),
            sa.Column("duration", sa.Float(), nullable=False),
            sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("lyrics", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column("musical_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column("music_change", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column("intensity", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column("mood", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("tempo", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("audio_evidence", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("transient_impact", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("audio_sync", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("transition_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("shot_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("camera_angle", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("camera_movement", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("composition", sa.JSON(), nullable=False),
            sa.Column("lighting", sa.JSON(), nullable=False),
            sa.Column("continuity_notes", sa.String(), server_default=sa.text("'[]'"), nullable=False),
            sa.Column("character_reference_ids", sa.String(), server_default=sa.text("'[]'"), nullable=False),
            sa.Column("location_reference_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("location_id", sa.Uuid(), nullable=False),
            sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("progress_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column("guidance_level", sa.Integer(), nullable=True),
            sa.Column("id", sa.Uuid(), nullable=False),
            sa.ForeignKeyConstraint(["location_id"], ["locations.id"]),
            sa.ForeignKeyConstraint(["project_id"], ["folder.id"]),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("id"),
        )
        with op.batch_alter_table("scenes", schema=None) as batch_op:
            batch_op.create_index("scenes_guidance_idx", ["guidance_level"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scenes", schema=None) as batch_op:
        batch_op.drop_index("scenes_guidance_idx")

    op.drop_table("scenes")
    # ### end Alembic commands ###
