"""add vertex_builds model

Phase: EXPAND

Revision ID: b2869e932bd3
Revises: 0dda306ba14b
Create Date: 2026-06-25 00:56:04.230905

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b2869e932bd3"
down_revision: str | None = "0dda306ba14b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vertex_build",
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("artifacts", sa.JSON(), nullable=True),
        sa.Column("params", sa.Text(), nullable=True),
        sa.Column("valid", sa.Boolean(), nullable=False),
        sa.Column("flow_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("build_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("build_id"),
    )
    with op.batch_alter_table("vertex_build", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_vertex_build_job_id"), ["job_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("vertex_build", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_vertex_build_job_id"))

    op.drop_table("vertex_build")
    # ### end Alembic commands ###
