"""add branch field to project_repository_link table

Phase: EXPAND

Revision ID: e1f2g3h4i5j6
Revises: 3100d8458a54
Create Date: 2026-07-06 13:46:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e1f2g3h4i5j6"  # pragma: allowlist secret
down_revision: str | None = "3100d8458a54"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_repository_link", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("branch", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_repository_link", schema=None) as batch_op:
        batch_op.drop_column("branch")
    # ### end Alembic commands ###
