import { generateEntityAttributes } from "#shared/lm/tools/generate-entity-attributes.js";
import { ToolContext } from "#shared/lm/tools/tools.utils.js";
import { TextModelController } from "../../text-model-controller.js";
import {
    CharacterAttributes,
    UploadResult,
} from "../../../types/index.js";
import { ProjectRepository } from "#shared/services/project-repository.js";

/**
 * Produces a complete CharacterAttributes object from a partial.
 * Fields already set by the caller are preserved exactly — only missing
 * or empty fields are generated by the LLM.
 */
export async function generateCharacterAttributes(
    inputs: {
        partial: Partial<CharacterAttributes> & { id: string };
        images?: UploadResult[];
    }[],
    context: ToolContext<TextModelController> & { projectRepository: ProjectRepository }
): Promise<CharacterAttributes[]> {

    const entityType = "character";
    const results = await generateEntityAttributes({
        schema: CharacterAttributes,
        entities: inputs.map(input => ({
            attributes: input.partial,
            entityType,
            images: input.images
        })),
        entityDescription: "character profile",
    },
        context
    );

    return results.map((result) => {
        if (!result.success) {
            throw new Error(`[Trace: ${context.traceId}] Failed to generate character attributes for ID ${result.id}: ${result.error?.message}`);
        }
        return result.attributes;
    });
}