import { generateEntityAttributes } from "#shared/lm/tools/generate-entity-attributes.js";
import { ToolContext } from "#shared/lm/tools/tools.utils.js";
import { TextModelController } from "../../text-model-controller.js";
import {
    PropAttributes,
    UploadResult,
} from "../../../types/index.js";
import { ProjectRepository } from "#shared/services/project-repository.js";

/**
 * Produces a complete PropAttributes object from a partial.
 * Fields already set by the caller are preserved exactly — only missing
 * or empty fields are generated by the LLM.
 */
export async function generatePropAttributes<T extends { id: string }>(
    inputs: {
        data: T & Partial<PropAttributes>;
        images?: UploadResult[];
    }[],
    context: ToolContext<TextModelController> & { projectRepository: ProjectRepository }
): Promise<(PropAttributes & T)[]> {

    const entityType = "prop";
    const results = await generateEntityAttributes({
        schema: PropAttributes,
        entities: inputs.map(input => ({
            data: input.data,
            entityType,
            images: input.images
        })),
        entityDescription: "prop profile",
    },
        context
    );

    return results.map((result) => {
        if (!result.success) {
            throw new Error(`[Trace: ${context.traceId}] Failed to generate prop attributes for ID ${result.data.id}: ${result.error?.message}`);
        }
        return result.data;
    });
}